/**
 * Application Error Codes
 *
 * Machine-readable error codes sent in API responses.
 * Each code maps to a specific failure scenario for easier frontend handling and logging.
 */

const ERROR_CODES = {
  // Generic Errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // Environment / Configuration Errors
  MISSING_ENV_VARIABLE: "MISSING_ENV_VARIABLE",
  INVALID_CONFIGURATION: "INVALID_CONFIGURATION",

  // Authentication Errors
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  MISSING_TOKEN: "MISSING_TOKEN",

  // Password / Account Errors
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",
  PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",

  // Resource Errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  EXPIRED_RESET_TOKEN: "EXPIRED_RESET_TOKEN",
};

module.exports = ERROR_CODES;
